CMake: Add path to dfdutils headers for toktx
That path was being added to the include dirs of the library ktx only
when `KTX_FEATURE_VULKAN` was enabled, resulting in a build failure
otherwise:

```
    /home/pmoreau/Softwares/KTX-Software/tools/toktx/pngimage.cc:26:10: fatal error: 'dfd.h' file not found
    #include "dfd.h"
             ^~~~~~~
    1 error generated.
```